<?php

namespace Database\Seeders;

use App\Models\Referral;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ReferralSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $referrals = [
            [
                "Hospital" => "City Hospital",
                "Name" => "John Doe",
                "Sex" => "m",
                "Age" => 45,
                "BloodGroup" => "A+",
                "LNMP" => null,
                "Gravida" => null,
                "Para" => null,
                "LCB" => null,
                "ReportedFrom" => "Home",
                "ReportedOn" => "2024-07-25",
                "Urgency" => "High",
                "PresentingComplaints" => [
                    "Chest pain",
                    "Shortness of breath",
                    "Dizziness",
                ],
                "Duration" => "2 days",
                "ExaminationFindings" => [
                    "Elevated blood pressure",
                    "Irregular heartbeat",
                    "Pale complexion",
                ],
                "WorkingDiagnosis" => "Myocardial infarction",
                "DifferentialDiagnosis" => ["Angina", "Pulmonary embolism"],
                "PreReferralManagement" => [
                    "Aspirin given",
                    "Oxygen administered",
                    "IV fluids started",
                ],
                "Procedure" => null,
                "Findings" => null,
                "ReasonsForReferral" => [
                    "Need for specialized care",
                    "Unstable condition",
                    "Further diagnostics",
                ],
                "DepartmentReferralDirected" => "Cardiology",
                "UnitsOfBlood" => 0,
                "ReferringOfficer" => "Dr. Smith",
                "Designation" => "GP",
                "NameDHO" => "Dr. Johnson",
                "Status" => "Requested",
            ],
            [
                "Hospital" => "General Hospital",
                "Name" => "Jane Smith",
                "Sex" => "f",
                "Age" => 34,
                "BloodGroup" => "O-",
                "LNMP" => "2024-06-20",
                "Gravida" => 2,
                "Para" => 1,
                "LCB" => 1,
                "ReportedFrom" => "H Center",
                "ReportedOn" => "2024-07-26",
                "Urgency" => "High",
                "PresentingComplaints" => ["Severe abdominal pain", "Nausea"],
                "Duration" => "1 day",
                "ExaminationFindings" => ["Tender abdomen", "Vomiting", "Pale complexion"],
                "WorkingDiagnosis" => "Ectopic pregnancy",
                "DifferentialDiagnosis" => ["Appendicitis", "Ovarian cyst rupture"],
                "PreReferralManagement" => ["IV fluids started", "Pain relief given"],
                "Procedure" => "Laparotomy",
                "Findings" => "Ruptured ectopic pregnancy",
                "ReasonsForReferral" => [
                    "Surgical intervention required",
                    "Patient's condition deteriorating",
                ],
                "DepartmentReferralDirected" => "Gynecology",
                "UnitsOfBlood" => 2,
                "ReferringOfficer" => "Dr. Adams",
                "Designation" => "Obstetrician",
                "NameDHO" => "Dr. Brown",
                "Status" => "Sent",
            ],
            [
                "Hospital" => "County Hospital",
                "Name" => "Michael Johnson",
                "Sex" => "m",
                "Age" => 52,
                "BloodGroup" => "B+",
                "LNMP" => null,
                "Gravida" => null,
                "Para" => null,
                "LCB" => null,
                "ReportedFrom" => "Home",
                "ReportedOn" => "2024-07-27",
                "Urgency" => "Medium",
                "PresentingComplaints" => ["Severe headache", "Blurred vision"],
                "Duration" => "3 days",
                "ExaminationFindings" => ["High blood pressure", "Neurological deficits"],
                "WorkingDiagnosis" => "Cerebral hemorrhage",
                "DifferentialDiagnosis" => ["Stroke", "Migraine"],
                "PreReferralManagement" => ["Blood pressure control", "CT scan done"],
                "Procedure" => null,
                "Findings" => null,
                "ReasonsForReferral" => [
                    "Neurological assessment required",
                    "Critical condition",
                ],
                "DepartmentReferralDirected" => "Neurology",
                "UnitsOfBlood" => 0,
                "ReferringOfficer" => "Dr. Clark",
                "Designation" => "Neurologist",
                "NameDHO" => "Dr. Harris",
                "Status" => "Accepted",
            ],
            [
                "Hospital" => "Regional Hospital",
                "Name" => "Emily Davis",
                "Sex" => "f",
                "Age" => 28,
                "BloodGroup" => "AB+",
                "LNMP" => "2024-07-10",
                "Gravida" => 1,
                "Para" => 0,
                "LCB" => 0,
                "ReportedFrom" => "TBA",
                "ReportedOn" => "2024-07-28",
                "Urgency" => "High",
                "PresentingComplaints" => ["Heavy vaginal bleeding", "Abdominal cramps"],
                "Duration" => "4 hours",
                "ExaminationFindings" => [
                    "Low blood pressure",
                    "Rapid pulse",
                    "Pale complexion",
                ],
                "WorkingDiagnosis" => "Miscarriage",
                "DifferentialDiagnosis" => ["Placental abruption", "Preterm labor"],
                "PreReferralManagement" => [
                    "IV fluids started",
                    "Blood transfusion initiated",
                ],
                "Procedure" => "D&C",
                "Findings" => "Incomplete miscarriage",
                "ReasonsForReferral" => [
                    "Urgent surgical intervention",
                    "Hemodynamic instability",
                ],
                "DepartmentReferralDirected" => "Obstetrics",
                "UnitsOfBlood" => 1,
                "ReferringOfficer" => "Dr. Lewis",
                "Designation" => "GP",
                "NameDHO" => "Dr. White",
                "Status" => "Under Treatment",
            ],
            [
                "Hospital" => "District Hospital",
                "Name" => "Chris Lee",
                "Sex" => "m",
                "Age" => 60,
                "BloodGroup" => "O+",
                "LNMP" => null,
                "Gravida" => null,
                "Para" => null,
                "LCB" => null,
                "ReportedFrom" => "Other",
                "ReportedOn" => "2024-07-29",
                "Urgency" => "Medium",
                "PresentingComplaints" => ["Fever", "Severe joint pain", "Rash"],
                "Duration" => "5 days",
                "ExaminationFindings" => [
                    "Elevated temperature",
                    "Swollen joints",
                    "Rash on trunk",
                ],
                "WorkingDiagnosis" => "Dengue fever",
                "DifferentialDiagnosis" => ["Malaria", "Chikungunya"],
                "PreReferralManagement" => ["Antipyretics given", "IV fluids started"],
                "Procedure" => null,
                "Findings" => null,
                "ReasonsForReferral" => [
                    "Specialized infectious disease care",
                    "Severe symptoms",
                ],
                "DepartmentReferralDirected" => "Infectious Diseases",
                "UnitsOfBlood" => 0,
                "ReferringOfficer" => "Dr. Martin",
                "Designation" => "GP",
                "NameDHO" => "Dr. Green",
                "Status" => "Referred Back",
            ],
            [
                "Hospital" => "Metropolitan Hospital",
                "Name" => "Sarah Kim",
                "Sex" => "f",
                "Age" => 50,
                "BloodGroup" => "B-",
                "LNMP" => "2024-07-05",
                "Gravida" => 3,
                "Para" => 2,
                "LCB" => 2,
                "ReportedFrom" => "Home",
                "ReportedOn" => "2024-07-30",
                "Urgency" => "Medium",
                "PresentingComplaints" => [
                    "Shortness of breath",
                    "Cough with sputum",
                    "Fatigue",
                ],
                "Duration" => "1 week",
                "ExaminationFindings" => [
                    "Crackles in lungs",
                    "Cyanosis",
                    "Low oxygen saturation",
                ],
                "WorkingDiagnosis" => "Pneumonia",
                "DifferentialDiagnosis" => ["COPD exacerbation", "Tuberculosis"],
                "PreReferralManagement" => ["Antibiotics started", "Oxygen therapy"],
                "Procedure" => null,
                "Findings" => null,
                "ReasonsForReferral" => [
                    "Respiratory support needed",
                    "Poor response to initial treatment",
                ],
                "DepartmentReferralDirected" => "Pulmonology",
                "UnitsOfBlood" => 0,
                "ReferringOfficer" => "Dr. Perez",
                "Designation" => "Pulmonologist",
                "NameDHO" => "Dr. Thompson",
                "Status" => "Discharged",
            ],
            [
                "Hospital" => "Suburban Hospital",
                "Name" => "David Brown",
                "Sex" => "m",
                "Age" => 72,
                "BloodGroup" => "A-",
                "LNMP" => null,
                "Gravida" => null,
                "Para" => null,
                "LCB" => null,
                "ReportedFrom" => "H Center",
                "ReportedOn" => "2024-07-31",
                "Urgency" => "Low",
                "PresentingComplaints" => ["Chest pain", "Shortness of breath", "Fatigue"],
                "Duration" => "2 days",
                "ExaminationFindings" => [
                    "Normal blood pressure",
                    "Clear lungs",
                    "No neurological deficits",
                ],
                "WorkingDiagnosis" => "Angina",
                "DifferentialDiagnosis" => ["Myocardial infarction", "Panic attack"],
                "PreReferralManagement" => ["Nitroglycerin given", "Oxygen therapy"],
                "Procedure" => null,
                "Findings" => null,
                "ReasonsForReferral" => [
                    "Need for cardiology consultation",
                    "Ongoing chest pain",
                ],
                "DepartmentReferralDirected" => "Cardiology",
                "UnitsOfBlood" => 0,
                "ReferringOfficer" => "Dr. Stewart",
                "Designation" => "GP",
                "NameDHO" => "Dr. Gray",
                "Status" => "Pending",
            ],
        ];

        foreach ($referrals as $referral) {
            Referral::create($referral);
        }

    }
}
